### ISSUE TITLE
CTFeedback.bundle to copy not found

### ISSUE THREAD

**Issue by mko-x** [rizumita/CTFeedback#25]
Using CTFeedback several months now, very nice and good to handle.

For some reason it adds a bundle path that should be a copied resource.

'''Pods/${BUILT_PRODUCTS_DIR}/CTFeedback.bundle'''

This path is not found later during processing:

project/Pods/${BUILT_PRODUCTS_DIR}/CTFeedback.bundle
building file list ... rsync: link_stat 
/Pods/${BUILT_PRODUCTS_DIR}/CTFeedback.bundle" failed: No such file or directory (2)

Any Idea?

**Comment by nagaho** [comment]
+1

**Comment by rizumita** [comment]
I think CTFeedback.bundle is placed at ${BUILT_PRODUCTS_DIR}/CTFeedback.bundle.

**Comment by nagaho** [comment]
It seems that Objective-C project works perfectly but Swift project does not work with filePath is null.  
> NSString *filePath = [bundle pathForResource:@"PlatformNames" ofType:@"plist"];

Env:
cocoapods-0.36.4
xcode-6.3.1

**Comment by sirnacnud** [comment]
This problem is caused by CTFeedback being built as a framework.  The same error will happen with objective-c if *use_frameworks!* is specified in your podfile.

I have created a pull request #27 to fix the problem.

**Comment by nagaho** [comment]
@sirnacnud It works perfectly. Thank you.
