### ISSUE TITLE
Keyboard not dismissing when adding image.

### ISSUE THREAD

**Issue by gbmksquare** [rizumita/CTFeedback#39]
If "Additional Info" is tapped to choose image while keyboard is still present, actionsheet is presented behind the keyboard and other views are grayed out.

Currently, user can get out of this state by tapping any view other than keyboard, and then scroll to dismiss the keyboard. Because actionsheet is dismissed when user do this, user doesn't know there was an actionsheet until they tap "Additional Info" again.

![2016-01-27 09 53 52](https://cloud.githubusercontent.com/assets/3669202/12600303/094b537a-c4dc-11e5-96b5-3d13f6f5933f.png)

**Comment by sirnacnud** [comment]
I fixed this problem in my fork, see sirnacnud/CTFeedback@4cc304a58c1eaf364e1af5d54dbdca2a3b81cd2e. I can create a PR for this to bring it in.

**Comment by gbmksquare** [comment]
@sirnacnud That'd be great thanks!

**Comment by rizumita** [comment]
@gbmksquare 
I close this issue.
Please create new issue if you need anything.
