### ISSUE TITLE
Please add Dutch translation 

### ISSUE THREAD

**Issue by FreshApps** [rizumita/CTFeedback#47]
"Question" = "Vraag";

"Request" = "Verzoek";

"Bug Report" = "Bug verslag";

"Other" = "Overig";

"Device" = "Toestel";

"iOS" = "iOS";

"Name" = "Naam";

"Version" = "Versie";

"Build" = "Build";

"Device Info" = "Toestel informatie";

"App Info" = "App informatie";

"Feedback" = "Feedback";

"Topic" = "Onderwerp";

"Topics" = "Topics";

"Error" = "Error";

"Mail" = "Mail";

"Mail no configuration"="Je hebt geen geldige e-mail account";

"Dismiss"="Sluiten";

"Additional Info"="Extra informatie";

"Additional detail"="Selecteer een afbeelding";

"Cancel"="Annuleren";

"Camera"="Camera";

"PhotoLibrary"="Selecteer uit album";

**Comment by rizumita** [comment]
@FreshApps 
Now CTFeedback has a new string 
```
"User detail"="User detail";
```
Please translate the string to dutch.

**Comment by rizumita** [comment]
This translation was imported by #51
