### ISSUE TITLE
Please add Swedish translation

### ISSUE THREAD

**Issue by DarkoKulakov** [rizumita/CTFeedback#49]
"Question" = "Förfrågan";

"Request" = "Förslag";

"Bug Report" = "Bugg";

"Other" = "Annan";

"Device" = "Enhet";

"iOS" = "iOS";

"Name" = "Namn";

"Version" = "Version";

"Build" = "Build";

"Device Info" = "Enhetsinformation ";

"App Info" = "App Info";

"Feedback" = "Feedback";

"Topic" = "Ämne";

"Topics" = "Ämnen";

"Error" = "Felmeddelande";

"Mail" = "Skicka";

"Mail no configuration"="Det går inte att verifiera ett giltligt epost-konto";

"Dismiss"="Avfärda";

"Additional Info"="Ytterligare information";

"Additional detail"="Välj bifogad fil(bild) ";

"Cancel"="Ångra";

"Camera"="Kamera";

"PhotoLibrary"="Välj från album";

"User detail"="Användardetaljer";

**Comment by rizumita** [comment]
Thank you for your translation.
I added Swedish translation on #52 .
